
#define DEF_SOUND_SHORTSWORDATTACK	0
#define DEF_SOUND_LONGSWORDATTACK	1
#define DEF_SOUND_BOWAIMING			2
#define DEF_SOUND_BOWSHOOT			3
#define DEF_SOUND_AXEATTACK			4
#define DEF_SOUND_MENDAMAGE			5
#define DEF_SOUND_WOMENDAMAGE		6
#define DEF_SOUND_WALKLAND			7
#define DEF_SOUND_WALKGLASS			8
#define DEF_SOUND_RUNLAND			9
#define DEF_SOUND_RUNGLASS			10
#define DEF_SOUND_MENDYING			11
#define DEF_SOUND_WOMENDYING		12
#define DEF_SOUND_BAREHANDHIT		13
#define DEF_SOUND_SWORDHIT			14
#define DEF_SOUND_MACEHIT			15
#define DEF_SOUND_ARROWHIT			16


