#define DEF_SPRID_MOUSECURSOR				0

#define DEF_SPRID_INTERFACE_SPRFONTS		22
#define DEF_SPRID_INTERFACE_ADDINTERFACE	27
#define DEF_SPRID_INTERFACE_SPRFONTS2		28
#define DEF_SPRID_INTERFACE_F1HELPWINDOWS	29
#define DEF_SPRID_INTERFACE_FONT1			30	
#define DEF_SPRID_INTERFACE_FONT2			31
// Crafting
#define DEF_SPRID_INTERFACE_CRAFTING		32

#define DEF_SPRID_INTERFACE_NEWMAPS1		35
#define DEF_SPRID_INTERFACE_NEWMAPS2		36
#define DEF_SPRID_INTERFACE_NEWMAPS3		37
#define DEF_SPRID_INTERFACE_NEWMAPS4		38
#define DEF_SPRID_INTERFACE_NEWMAPS5		39 

#define DEF_SPRID_INTERFACE_MONSTER			50
#define DEF_SPRID_INTERFACE_ND_LOADING		51
#define DEF_SPRID_INTERFACE_ND_MAINMENU		52
#define DEF_SPRID_INTERFACE_ND_LOGIN		53
#define DEF_SPRID_INTERFACE_ND_NEWACCOUNT	54
#define DEF_SPRID_INTERFACE_ND_QUIT			55
#define DEF_SPRID_INTERFACE_ND_AGREEMENT	56
#define DEF_SPRID_INTERFACE_ND_SELECTCHAR	57
#define DEF_SPRID_INTERFACE_ND_NEWCHAR		58
#define DEF_SPRID_INTERFACE_ND_NEWEXCHANGE	59
#define DEF_SPRID_INTERFACE_ND_GAME1		60
#define DEF_SPRID_INTERFACE_ND_GAME2		61
#define DEF_SPRID_INTERFACE_ND_GAME3		62
#define DEF_SPRID_INTERFACE_ND_GAME4		63
#define DEF_SPRID_INTERFACE_ND_ICONPANNEL	64
#define DEF_SPRID_INTERFACE_ND_INVENTORY	67
#define DEF_SPRID_INTERFACE_ND_TEXT			70
#define DEF_SPRID_INTERFACE_ND_BUTTON		71
#define DEF_SPRID_INTERFACE_ND_CRUSADE		72
#define DEF_SPRID_INTERFACE_GUIDEMAP		420 // Snoopy:73 ->420 pour ajout de minimaps v3.51 (450 sur la 351)

#define DEF_SPRID_INTERFACE_FEEDBACK1		40
#define DEF_SPRID_INTERFACE_FEEDBACK2		41
#define DEF_SPRID_INTERFACE_FEEDBACK3		42
#define DEF_SPRID_INTERFACE_FEEDBACK4		43
#define DEF_SPRID_INTERFACE_FEEDBACK5		44
#define DEF_SPRID_INTERFACE_FEEDBACK6		45
#define DEF_SPRID_INTERFACE_FEEDBACK7		46


//#define DEF_SPRID_BGTILE_PIVOTPOINT			200 //  
//#define DEF_SPRID_EFFECT_PIVOTPOINT			20500 // 22000
#define DEF_SPRID_ITEMGROUND_PIVOTPOINT		100 //60
#define DEF_SPRID_ITEMEQUIP_PIVOTPOINT		200 //80
#define DEF_SPRID_ITEMPACK_PIVOTPOINT		300 //120
#define DEF_SPRID_ITEMDYNAMIC_PIVOTPOINT	400 //160
//#define DEF_SPRID_ITEMGROUND_PIVOTPOINT		20060 //60
//#define DEF_SPRID_ITEMEQUIP_PIVOTPOINT		20100 //80
//#define DEF_SPRID_ITEMPACK_PIVOTPOINT		20180 //120
//#define DEF_SPRID_ITEMDYNAMIC_PIVOTPOINT	20240 //160

// Snoopy: remplace par des macros pour pouvoir ajuster facilement....
//         sinon les mobs ecrasent la suite !
#define DEF_SPRID_MOB			17000

#define DEF_SPRID_UNDIES_M		1400	// 4580 
#define DEF_SPRID_UNDIES_W		11400
#define DEF_SPRID_HAIR_M		1600	// 13 hairs max
#define DEF_SPRID_HAIR_W		11600	// 13 hairs max
#define DEF_SPRID_BODYARMOR_M	1800	// 19 armors max
#define DEF_SPRID_BODYARMOR_W	11800	// 19 armors max
#define DEF_SPRID_BERK_M		2100	// 13 berks max
#define DEF_SPRID_BERK_W		12100	// 13 berks max
#define DEF_SPRID_LEGG_M		2300	// 13 leggings max
#define DEF_SPRID_LEGG_W		12300	// 13 leggings max	
#define DEF_SPRID_BOOT_M		2500	//  6 boots max	
#define DEF_SPRID_BOOT_W		12500	//  6 boots max	
#define DEF_SPRID_MANTLE_M		2600	// 10 capes max	
#define DEF_SPRID_MANTLE_W		12600	// 10 capes max	
#define DEF_SPRID_HEAD_M		2750	// 16 casques max	
#define DEF_SPRID_HEAD_W		12750	// 16 casques max	

#define DEF_SPRID_WEAPON_M		3000	// 54 armes max 
#define DEF_SPRID_WEAPON_W		13000	// 54 armes max 

#define DEF_SPRID_SHIELD_M		6500	// 
#define DEF_SPRID_SHIELD_W		16500

//Snoopy: Angels
#define DEF_SPRID_TUTELARYANGELS_PIVOTPOINT 10800

//         sinon les mobs ecrasent la suite !
/*#define DEF_SPRID_MOB			1220

#define DEF_SPRID_UNDIES_M		4580 
#define DEF_SPRID_UNDIES_W		14580
#define DEF_SPRID_HAIR_M		4820
#define DEF_SPRID_HAIR_W		14820
#define DEF_SPRID_BODYARMOR_M	5060
#define DEF_SPRID_BODYARMOR_W	15060
#define DEF_SPRID_BERK_M		5300
#define DEF_SPRID_BERK_W		15300
#define DEF_SPRID_LEGG_M		5540
#define DEF_SPRID_LEGG_W		15540
#define DEF_SPRID_BOOT_M		5780
#define DEF_SPRID_BOOT_W		15780
#define DEF_SPRID_MANTLE_M		9230
#define DEF_SPRID_MANTLE_W		19230
#define DEF_SPRID_HEAD_M		9300
#define DEF_SPRID_HEAD_W		19300

#define DEF_SPRID_WEAPON_M		6020 
#define DEF_SPRID_WEAPON_W		16020

#define DEF_SPRID_SHIELD_M		9100
#define DEF_SPRID_SHIELD_W		19100*/