#define DEF_TOTALACTION			10

#define DEF_OBJECTSTOP			0
#define DEF_OBJECTMOVE			1
#define DEF_OBJECTRUN			2
#define DEF_OBJECTATTACK		3
#define DEF_OBJECTMAGIC			4
#define DEF_OBJECTGETITEM		5
#define DEF_OBJECTDAMAGE		6
#define DEF_OBJECTDAMAGEMOVE	7
#define DEF_OBJECTATTACKMOVE	8
#define DEF_OBJECTDYING			10			   
#define DEF_OBJECTNULLACTION	100

#define DEF_OBJECTMOVE_CONFIRM				1001
#define DEF_OBJECTMOVE_REJECT				1010
#define DEF_OBJECTMOTION_CONFIRM			1020
#define DEF_OBJECTMOTION_ATTACK_CONFIRM		1030
#define DEF_OBJECTMOTION_REJECT				1040


