
#define DEF_DYNAMICOBJECT_FIRE			1
#define DEF_DYNAMICOBJECT_FISH			2
#define DEF_DYNAMICOBJECT_FISHOBJECT	3
#define DEF_DYNAMICOBJECT_MINERAL1		4
#define DEF_DYNAMICOBJECT_MINERAL2		5
#define DEF_DYNAMICOBJECT_ARESDENFLAG1	6
#define DEF_DYNAMICOBJECT_ELVINEFLAG1	7
#define DEF_DYNAMICOBJECT_ICESTORM		8
#define DEF_DYNAMICOBJECT_SPIKE			9
#define DEF_DYNAMICOBJECT_PCLOUD_BEGIN	10
#define DEF_DYNAMICOBJECT_PCLOUD_LOOP	11
#define DEF_DYNAMICOBJECT_PCLOUD_END	12
#define DEF_DYNAMICOBJECT_FIRE2			13 // Crusade's Meteor strike
#define DEF_DYNAMICOBJECT_FIRE3			14 // for FireBow

#define DEF_DYNAMICOBJECT_STATUE1		15 // Snoopy Avatar quest
#define DEF_DYNAMICOBJECT_STATUE2		16 // Snoopy Avatar quest
#define DEF_DYNAMICOBJECT_STATUE3		17 // Snoopy Avatar quest
#define DEF_DYNAMICOBJECT_STATUE4		18 // Snoopy Avatar quest
#define DEF_DYNAMICOBJECT_STATUE5		19 // Snoopy Avatar quest
#define DEF_DYNAMICOBJECT_STATUE6		20 // Snoopy Avatar quest
#define DEF_DYNAMICOBJECT_STATUE7		21 // Snoopy Avatar quest