
#define DEF_INDEX4_MSGID			0
#define DEF_INDEX2_MSGTYPE			4

/*
#define DEF_INDEX2_LOCX				6
#define DEF_INDEX2_LOCY				8
#define DEF_INDEX2_OBJECTTYPE		10
#define DEF_INDEX1_DIR				12
#define DEF_INDEX2_APPEARANCE1		23
#define DEF_INDEX2_APPEARANCE2		25
#define DEF_INDEX2_APPEARANCE3		27
#define DEF_INDEX2_APPEARANCE4		29
#define DEF_INDEX2_STATUS			31
#define DEF_INDEX2_VALUE1			33
#define DEF_INDEX2_VALUE2			35
#define DEF_INDEX2_VALUE3			37

#define DEF_INDEX20_COMMAND_STRING	13
#define DEF_INDEX2_COMMAND_V1		13
#define DEF_INDEX2_COMMAND_V2		15		 
#define DEF_INDEX2_COMMAND_V3		17
#define DEF_INDEX2_COMMAND_V4		19

#define DEF_INDEX2_COMMON_VALUE1	10
#define DEF_INDEX2_COMMON_VALUE2	12
#define DEF_INDEX2_COMMON_VALUE3	14

#define DEF_INDEX10_NAME			13
#define DEF_INDEX10_CHATNAME		10

#define DEF_INDEXX_MOVEMAPDATA		13 //33
#define DEF_INDEX10_MAPNAME			33
#define DEF_INDEXX_INITMAPDATA		43
#define DEF_INDEXX_CHATMSG			20

#define DEF_INDEX10_INIT_CHARNAME		6
#define DEF_INDEX10_INIT_ACCNTNAME		16
#define DEF_INDEX10_INIT_ACCNTPASSWORD	26
#define DEF_INDEX20_INIT_GUILDNAME		36
#define DEF_INDEX50_INIT_EMAILADDR		36
#define DEF_INDEXXX_INIT_PLAYERDATA		36
#define DEF_INDEX16_INIT_ADDRESS		26
#define DEF_INDEX2_INIT_PORT			42
#define DEF_INDEX1_INIT_TOTALMAPS		44
#define DEF_INDEXX_INIT_MAPLIST			45

#define DEF_INDEX1_INIT_TOTALCHARACTERS	6
#define DEF_INDEX1_INIT_ACCOUNTSTATUS	16
#define DEF_INDEXX_INIT_CHARACTERINFO	17
#define DEF_INDEX1_INIT_GUILDSTATUS		17
#define DEF_INDEX1_INIT_GUILDSMANNUM	18

#define DEF_INDEXX_INIT_NOTIFYINFO		6
#define DEF_INDEX1_INIT_TOTALITEMS		6
#define DEF_INDEXX_INIT_ITEMCONTENTS	7

#define DEF_INDEX4_INIT_HITPOINT		6
#define DEF_INDEX4_INIT_ARMORCLASS		10
#define DEF_INDEX4_INIT_THAC0			14
#define DEF_INDEX4_INIT_LEVEL			18
#define DEF_INDEX4_INIT_STR				22
#define DEF_INDEX4_INIT_INT				26
#define DEF_INDEX4_INIT_VIT				30
#define DEF_INDEX4_INIT_DEX				56
#define DEF_INDEX4_INIT_MAG				60
#define DEF_INDEX4_INIT_EXP				64
#define DEF_INDEX4_INIT_CHARISMA		68
#define DEF_INDEX4_INIT_GUILDRANK		72
*/
